### PR TITLE
Update deprecated github actions

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?

This PR updates specific github actions to latest version in order to use NodeJS 16 and not NodeJS 12.
The updated github actions are:

- `actions/checkout@v2` > `actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3`
- `actions/setup-go@v2` > `actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0`

### What issues does this PR fix or reference?

fixes https://github.com/devfile/api/issues/1229

### Is your PR tested? Consider putting some instruction how to test your changes
The PR simply updates the `gotest.yaml` workflow in order to use the latest version of two github actions.

### CODE REVIEW

**Review by kim-tsao — APPROVED** [review]

**Comment by michael-valdron** [comment]
fixes devfile/api#1249

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
