### PR TITLE
Use the latest ODO codes for devfile integration test

### PR DESCRIPTION
**Pull request by josephca**
### What does this PR do?
Update devfile integration test for Odo v2.0.1

### CODE REVIEW

**Comment by amitkrout** [comment]
@josephca odo is running the same test against 4.2, 4.3, 4.5 and 4.6 through pr job and periodic job. Lets not duplicate the effort.

Lets run devfile integration test against latest odo master by writing a script that clone the odo master branch and run the devfile specific test through ```devfile/integration-tests``` pr and periodic job.

```bash
$ cat devfiletest.sh
#!/bin/sh

# fail if some commands fails
set -e
# show commands
set -x

export CI="openshift"
make configure-installer-tests-cluster
make bin
mkdir -p $GOPATH/bin
make goget-ginkgo
export PATH="$PATH:$(pwd):$GOPATH/bin"
export ARTIFACTS_DIR="/tmp/artifacts"
export CUSTOM_HOMEDIR=$ARTIFACTS_DIR

# Copy kubeconfig to temporary kubeconfig file
# Read and Write permission to temporary kubeconfig file
TMP_DIR=$(mktemp -d)
cp $KUBECONFIG $TMP_DIR/kubeconfig
chmod 640 $TMP_DIR/kubeconfig
export KUBECONFIG=$TMP_DIR/kubeconfig

# Login as developer
odo login -u developer -p password@123

# Check login user name for debugging purpose
oc whoami
make test-integration-devfile

cp -r reports $ARTIFACTS_DIR 

odo logout
```

I will share the detail steps on how to do it in my next comment.

**Review by amitkrout — CHANGES_REQUESTED** [review]
The plan is to provide an integration endpoint for tolling like odo and others to execute their respective test for early feedback on any changes made by devfile org. Early feedback may help the devfile user to adapt with new changes and fix them from their end too, or fix from devfile end will be provided depending upon the use case. 

The test flow would be like CI will run for each pr in the test repo to verify the current test script changes and ofcourse we need a periodic run let say in the interval of 5hrs. Periodic run because we are not running integration/e2e tests against repo like api, library, parser etc, so a periodic run against each supported tooling in the test repo would help us to provide feedback for the changes that merges into api, library etc.

The repo structure would be 

```bash
$ tree
.
├── LICENSE
├── OWNERS
├── README.md
├── openshift-ci
│   └── build-root
│       ├── Dockerfile
│       └── source-image
│           └── Dockerfile
└── scripts
    └── openshiftci-presubmit-all-tests.sh

4 directories, 6 files
```

```bash
$ cat scripts/openshiftci-presubmit-all-tests.sh 
#!/bin/sh

# fail if some commands fails
set -e
# show commands
set -x

git clone https://github.com/openshift/odo $GOPATH/src/github.com/openshift/odo
cd $GOPATH/src/github.com/openshift/odo

export CI="openshift"
make configure-installer-tests-cluster
make bin
mkdir -p $GOPATH/bin
make goget-ginkgo
export PATH="$PATH:$(pwd):$GOPATH/bin"
export ARTIFACTS_DIR="/tmp/artifacts"
export CUSTOM_HOMEDIR=$ARTIFACTS_DIR

# Copy kubeconfig to temporary kubeconfig file
# Read and Write permission to temporary kubeconfig file
TMP_DIR=$(mktemp -d)
cp $KUBECONFIG $TMP_DIR/kubeconfig
chmod 640 $TMP_DIR/kubeconfig
export KUBECONFIG=$TMP_DIR/kubeconfig

# Login as developer
odo login -u developer -p password@123

# Check login user name for debugging purpose
oc whoami

make test-integration-devfile

cp -r reports $ARTIFACTS_DIR

odo logout
```

Once this is verified and merged then we have to work on periodic job.

**Comment by amitkrout** [comment]
@josephca You need to create another pr in release repo to consume the file ```openshiftci-presubmit-devfiles-tests.sh``` after pr #6 goes into master.

**Comment by josephca** [comment]
> @josephca odo is running the same test against 4.2, 4.3, 4.5 and 4.6 through pr job and periodic job. Lets not duplicate the effort.
> 
> Lets run devfile integration test against latest odo master on the fly by writing a script that clone the odo master branch and run the devfile specific test through `devfile/integration-tests` pr and periodic job.
> 
> ```shell
> $ cat devfiletest.sh
> #!/bin/sh
> 
> # fail if some commands fails
> set -e
> # show commands
> set -x
> 
> git clone https://github.com/openshift/odo $GOPATH/src/github.com/openshift/odo
> cd $GOPATH/src/github.com/openshift/odo
> 
> export CI="openshift"
> make configure-installer-tests-cluster
> make bin
> mkdir -p $GOPATH/bin
> make goget-ginkgo
> export PATH="$PATH:$(pwd):$GOPATH/bin"
> export ARTIFACTS_DIR="/tmp/artifacts"
> export CUSTOM_HOMEDIR=$ARTIFACTS_DIR
> 
> # Copy kubeconfig to temporary kubeconfig file
> # Read and Write permission to temporary kubeconfig file
> TMP_DIR=$(mktemp -d)
> cp $KUBECONFIG $TMP_DIR/kubeconfig
> chmod 640 $TMP_DIR/kubeconfig
> export KUBECONFIG=$TMP_DIR/kubeconfig
> 
> # Login as developer
> odo login -u developer -p password@123
> 
> # Check login user name for debugging purpose
> oc whoami
> make test-integration-devfile
> 
> cp -r reports $ARTIFACTS_DIR 
> 
> odo logout
> ```
> 
> I will share the detail steps on how to do it in my next comment.



> @josephca odo is running the same test against 4.2, 4.3, 4.5 and 4.6 through pr job and periodic job. Lets not duplicate the effort.
> 
> Lets run devfile integration test against latest odo master on the fly by writing a script that clone the odo master branch and run the devfile specific test through `devfile/integration-tests` pr and periodic job.
> 
> ```shell
> $ cat devfiletest.sh
> #!/bin/sh
> 
> # fail if some commands fails
> set -e
> # show commands
> set -x
> 
> git clone https://github.com/openshift/odo $GOPATH/src/github.com/openshift/odo
> cd $GOPATH/src/github.com/openshift/odo
> 
> export CI="openshift"
> make configure-installer-tests-cluster
> make bin
> mkdir -p $GOPATH/bin
> make goget-ginkgo
> export PATH="$PATH:$(pwd):$GOPATH/bin"
> export ARTIFACTS_DIR="/tmp/artifacts"
> export CUSTOM_HOMEDIR=$ARTIFACTS_DIR
> 
> # Copy kubeconfig to temporary kubeconfig file
> # Read and Write permission to temporary kubeconfig file
> TMP_DIR=$(mktemp -d)
> cp $KUBECONFIG $TMP_DIR/kubeconfig
> chmod 640 $TMP_DIR/kubeconfig
> export KUBECONFIG=$TMP_DIR/kubeconfig
> 
> # Login as developer
> odo login -u developer -p password@123
> 
> # Check login user name for debugging purpose
> oc whoami
> make test-integration-devfile
> 
> cp -r reports $ARTIFACTS_DIR 
> 
> odo logout
> ```
> 
> I will share the detail steps on how to do it in my next comment.

@amitkrout Thanks for the feedback and I agree to bring in and test with the latest odo code on the fly. Yes, I, also, was going to add the periodic execution of the tests after this PR gets merged first. :)

**Comment by amitkrout** [comment]
Unit test is failing due to 
```
 make: *** No rule to make target `openshiftci-presubmit-unittests'.  Stop.
error: failed to execute wrapped command: exit status 2 
```
We don't need Unit test CI verification in the test integration repo. @josephca Please create a pr to remove https://github.com/openshift/release/blob/master/ci-operator/config/devfile/integration-tests/devfile-integration-tests-master.yaml from OpenShift release repo.

How to remove:
1. Checkout a new branch in release repo
2. Delete the file https://github.com/openshift/release/blob/master/ci-operator/config/devfile/integration-tests/devfile-integration-tests-master.yaml
3. Run ```make jobs```
4. Commit the changes and push the branch

**Comment by amitkrout** [comment]
Looping odo QE @prietyc123 for more guidance.

**Comment by josephca** [comment]
> Unit test is failing due to
> 
> ```
>  make: *** No rule to make target `openshiftci-presubmit-unittests'.  Stop.
> error: failed to execute wrapped command: exit status 2 
> ```
> 
> We don't need Unit test CI verification in the test integration repo. @josephca Please create a pr to remove https://github.com/openshift/release/blob/master/ci-operator/config/devfile/integration-tests/devfile-integration-tests-master.yaml from OpenShift release repo.
> 
> How to remove:
> 
> 1. Checkout a new branch in release repo
> 2. Delete the file https://github.com/openshift/release/blob/master/ci-operator/config/devfile/integration-tests/devfile-integration-tests-master.yaml
> 3. Run `make jobs`
> 4. Commit the changes and push the branch

Agreed and removing the place holder unit test by https://github.com/openshift/release/pull/15136

**Comment by josephca** [comment]
@amitkrout I think _ci/prow/v4.5-integration-e2e_  is expected to be failed until the script file used by this PR and ci-operator config/job are in-synch. So, I suggest merging this PR first then fix the ci-operator config/job afterward. Any suggestion?

**Pull request merged**
