### PR TITLE
Add slack notification for devfile go integration tests

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?

This PR adds slack notification step to the `devfile go integration tests` workflow.

### What issues does this PR fix or reference?

Fixes https://github.com/devfile/api/issues/1026

### CODE REVIEW

**Comment by thepetk** [comment]
> WIP because we will have to add `SLACK_CHANNEL_ID` & `SLACK_WEBHOOK_URL` secrets

Removed WIP because both secrets are now added to the repo

**Review by michael-valdron — APPROVED** [review]
/lgtm

Aside from unrelated console failures.

**Comment by thepetk** [comment]
Although I think this is un-related to the current PR, I've been investigating the failures of the `openshift-ci` for `v4.1*.console-images` checks:

* In all previous PRs the console-images checks I see they were not failing. Last PR was merged in late November 2023 and was ok.
* The reason that all checks are failing is a syntax error of unexpected token `??=` which comes from  `compiler.options.output.uniqueName ??= containerName;` from the [dynamic-plugin-sdk](https://github.com/openshift/dynamic-plugin-sdk/blob/1c71da40a72775becd089b345d0e1449513c8c51/packages/lib-webpack/src/webpack/DynamicRemotePlugin.ts#L217) repo. 
* I've noticed that all other devfile checks inside the [openshift/release](https://github.com/openshift/release/tree/master/ci-operator/config/devfile) use a different (to my understanding newer base image).

From all the above I was wondering if it would be a good idea to bump up the [base image](https://github.com/openshift/release/blob/master/ci-operator/config/devfile/integration-tests/devfile-integration-tests-main__v4.10.console.yaml#L2-L5) used for this check as the error may comes from a breaking change or an incompatible dependency?

For the current PR I think is good to be merged.

cc @michael-valdron @johnmcollier

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
